package net.primal.networking.relays.errors

class NostrPublishException(override val cause: Throwable?) : RuntimeException()
